version: '2.0'

services :
  server_mongo_docker:
    image: server_mongo_docker
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3080:3080
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: 
